# Generated by Django 6.0.2 on 2026-06-24 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('scheduled_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('penalty_accrued', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_overdue', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['loan_application', 'month'],
                'unique_together': {('loan_application', 'month')},
            },
        ),
    ]
