# Generated by Django 6.0.6 on 2026-06-29 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanapplication_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('allocation_order', models.CharField(default='penalty,interest,principal', help_text='Comma-separated allocation order. Example: penalty,interest,principal', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_rules', to='loans.loanproduct')),
            ],
            options={
                'ordering': ['loan_product', 'name'],
                'unique_together': {('loan_product', 'name')},
            },
        ),
    ]
